### PR TITLE
Replace capital letters in logs

### PR DESCRIPTION
**Pull request by UsamaAmjad**

### CODE REVIEW

**Comment by noseglid** [comment]
I think this is all good, they're all errors which will be printed somewhere else

**Comment by UsamaAmjad** [comment]
> I think this is all good, they're all errors which will be printed somewhere else

So fmt.Errorf() and errors.New() are the same thing except formatting?

**Comment by noseglid** [comment]
Yes exactly. `errors.New` doesn't accept a format, but they both return an error interface.

**Review by noseglid — APPROVED** [review]
👍

**Pull request merged**
